### ISSUE TITLE
【建议】新增菜单的图标默认颜色略浅，建议加深颜色

### ISSUE THREAD

**Issue by 2015WUJI01** [laravel-admin-extensions/material-ui#5]
只有鼠标移上去时才会加深颜色，有些不合理，建议做适当修改^_^

![image](https://user-images.githubusercontent.com/24295778/50379940-ca917400-0693-11e9-8598-50d2914f3947.png)

**Comment by jxlwqq** [comment]
Fixed.
Update command:
```bash
composer update jxlwqq/material-ui
php artisan vendor:publish --tag=laravel-admin-material-ui --force
```

**Comment by jxlwqq** [comment]
![image](https://user-images.githubusercontent.com/2421068/50394942-f39d2c00-079b-11e9-8e67-089f76073991.png)
color 改成了 #aaaaaa
