### ISSUE TITLE
grid中一个属性貌似有问题

### ISSUE THREAD

**Issue by ghost** [laravel-admin-extensions/material-ui#8]
![](https://image-qxwa-static.cn-sh2.ufileos.com/github%2Fmaterial.png)
这个错位，强迫症要疯。
![](https://image-qxwa-static.cn-sh2.ufileos.com/github%2Fmaterial1.png)
定位到该文件。
修改 `margin:1px 1px;` ok.
![](https://image-qxwa-static.cn-sh2.ufileos.com/github%2Fmaterial2.png)
最后感谢作者做出这么精美的插件！

**Comment by jxlwqq** [comment]
已修复，使用以下命令升级：
```bash
composer update jxlwqq/material-ui
php artisan vendor:publish --tag=laravel-admin-material-ui --force
```
